spring:
  application:
    name: gulimall-search
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
elasticsearch:
  HttpHost: 192.168.145.128
  port: 9200
  scheme: "http"
server:
  port: 12000